version: '3'
services:
  app:
    image: aidarbek/app:latest
    build: .
    command: app
    volumes:
      - ".:/app"
    environment:
      PYTHONUNBUFFERED: 0
      PYTHONIOENCODING: utf-8
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
  bot:
    image: aidarbek/bot:v1
    build: .
    command: bot
    volumes:
      - ".:/app"
    environment:
      PYTHONUNBUFFERED: 0
      PYTHONIOENCODING: utf-8
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
