version: '3'
services:
  app:
    image: aidarbek/app:v1
    build: .
    command: app
    volumes:
      - ".:/app"
    environment:
      PYTHONUNBUFFERED: 0
      PYTHONIOENCODING: utf-8
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_RATELIMIT_ENABLED: "false"
  bot:
    image: aidarbek/bot:v1
    build: .
    command: bot
    volumes:
      - ".:/app"
    environment:
      PYTHONUNBUFFERED: 0
      PYTHONIOENCODING: utf-8
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery,schemas"
      WORKERS_COUNT: 2
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
